### ISSUE TITLE
Parinfer paste

### ISSUE THREAD

**Issue by awb99** [pink-gorilla/notebook#10]
I was pasting vega spec from some other workbook to a gorilla notebook cell. And the result that I got pasted in was different to what I had in the clipboard. 

{:data {:values [ 1 2 3]}}

Was pasted as:

{:data {}} 
:values [] 
123

My data structure was a little more complex.. So illustration only.

I think there needs to be an option to disable parinfer. When writing new code parinfee mode is a huge plus, but when using snippets it is impossible to impoet them

Ctrl g p
Toggle parinfer mode

**Comment by awb99** [comment]
It might be linked to formatting. So say "] )" instead of "])" might lead to parinfer re-arranging stuff.
Not 100% sure.

**Comment by awb99** [comment]
saite uses codemirror with paredit:
https://github.com/jsa-aerial/saite/blob/master/src/cljs/paredit_cm/core.cljs
https://github.com/jsa-aerial/saite/blob/master/src/cljs/aerial/saite/codemirror.cljs

**Comment by awb99** [comment]
https://github.com/jaredly/reepl/blob/master/src/reepl/code_mirror.cljs

**Comment by awb99** [comment]
https://github.com/jaredly/reepl

GREAT AUTOCOMPLETE AND DOCS!!

**Comment by awb99** [comment]
klipse

https://github.com/viebel/klipse/blob/master/src/klipse/ui/editors/editor.cljs

**Comment by awb99** [comment]
https://github.com/raymcdermott/reptile-tongue
reptile also uses parinfer.

**Comment by deas** [comment]
Not sure why, but I cannot reproduce the issue with current master (`9f9dab4c093fcd3990e51aa63cd911c7b094667c`). May haven been fixed by the mass upgrade which also included a recent version of codemirror.

**Comment by deas** [comment]
Can (no longer?) reproduce.

**Comment by awb99** [comment]
yippie! I tested today and bug is gone!

**Comment by awb99** [comment]
@deas  I suggest you make a markdown document listing "stealing options". this ticket contains some good references that we dont want to loose.

**Comment by awb99** [comment]
put into a code cell:
(pinkgorilla.kernel.cljs-tools/r!)

then paste the svg structure to the formula
```
[:svg
  {:viewbox "-10 -10 116 111"}
  [:path
   {:d
    "     M0,0     h7.75     a45.5,45.5 0 1 1 0,91     h-7.75     v-20     h7.75     a25.5,25.5 0 1 0 0,-51     h-7.75     z     m36.2510,0     h32     a27.75,27.75 0 0 1 21.331,45.5     a27.75,27.75 0 0 1 -21.331,45.5     h-32     a53.6895,53.6895 0 0 0 18.7464,-20     h13.2526     a7.75,7.75 0 1 0 0,-15.5     h-7.75     a53.6895,53.6895 0 0 0 0,-20     h7.75     a7.75,7.75 0 1 0 0,-15.5     h-13.2526     a53.6895,53.6895 0 0 0 -18.7464,-20     z   ",
    :fill "#bbb"}]
  [:g
   {:stroke-opacity "0.3",
    :stroke-width "0.15",
    :stroke "currentColor",
    :fill "none"}
   [:line {:y2 "0", :y1 "0", :x2 "200", :x1 "-100"}]
   [:line {:y2 "20", :y1 "20", :x2 "200", :x1 "-100"}]
   [:line {:y2 "35.5", :y1 "35.5", :x2 "200", :x1 "-100"}]
   [:line {:y2 "45.5", :y1 "45.5", :x2 "200", :x1 "-100"}]
   [:line {:y2 "55.5", :y1 "55.5", :x2 "200", :x1 "-100"}]
   [:line {:y2 "71", :y1 "71", :x2 "200", :x1 "-100"}]
   [:line {:y2 "91", :y1 "91", :x2 "200", :x1 "-100"}]
   [:line {:y2 "200", :y1 "-100", :x2 "0", :x1 "0"}]
   [:line {:y2 "200", :y1 "-100", :x2 "7.75", :x1 "7.75"}]
   [:line {:y2 "200", :y1 "-100", :x2 "60.5", :x1 "60.5"}]
   " "
   "<!-- XXX  -->"
   [:line {:y2 "200", :y1 "-100", :x2 "68.25", :x1 "68.25"}]
   [:line {:y2 "200", :y1 "-100", :x2 "96", :x1 "96"}]]
  [:g
   {:fill "blue"}
   [:circle {:r ".5", :cy "45.5", :cx "7.75"}]
   [:circle {:r ".5", :cy "27.75", :cx "68.25"}]
   [:circle {:r ".5", :cy "63.25", :cx "68.25"}]]
  [:g
   {:fill "red"}
   "<!-- Intersecting horizontal lines with the r=53.6895 circle. -->"
   [:circle {:r ".5", :cy "0", :cx "36.2510"}]
   [:circle {:r ".5", :cy "20", :cx "54.9974"}]
   [:circle {:r ".5", :cy "35.5", :cx "60.5"}]
   [:circle {:r ".5", :cy "55.5", :cx "60.5"}]
   [:circle {:r ".5", :cy "71", :cx "54.9974"}]
   [:circle {:r ".5", :cy "91", :cx "36.2510"}]
   "<!-- Intersecting the two r=27.75 circles. -->"
   [:circle {:r ".5", :cy "45.5", :cx "89.5807"}]]
  [:g
   {:stroke-width "0.15", :stroke "currentColor", :fill "none"}
   [:circle {:r "25.5", :cy "45.5", :cx "7.75"}]
   [:circle {:r "45.5", :cy "45.5", :cx "7.75"}]
   "<!-- Radius is computed to intersect at the intended x=60.5. -->"
   [:circle {:r "53.6895", :cy "45.5", :cx "7.75"}]
   [:circle {:r "7.75", :cy "27.75", :cx "68.25"}]
   [:circle {:r "27.75", :cy "27.75", :cx "68.25"}]
   [:circle {:r "7.75", :cy "63.25", :cx "68.25"}]
   [:circle {:r "27.75", :cy "63.25", :cx "68.25"}]]]

```

**Comment by awb99** [comment]
there is restore parinfer ticket that is open
