### ISSUE TITLE
Saving to file with empty breaks the current notebook

### ISSUE THREAD

**Issue by rrrnld** [pink-gorilla/notebook#126]
As noted in #125, I just started using this and I'll continue to provide feedback and hope this will be useful. Environment: Firefox 75.0, Arch Linux, gorilla-notebook version 0.4.9.

## Expected behavior

I expected the form to be validated or a file name generated from my namespace before I save.

## Actual behavior

Saving to file threw an error, left me with an empty page and unable to get back to the state of my notebook just before I saved.

**Comment by deas** [comment]
Just to make sure we are talking about the same thing:

We had a fairly big update yesterday rolling to 0.4.13. Please make sure to report against the latest version and check [the documentation](https://pink-gorilla.github.io/) once in a while. ;)

**Comment by rrrnld** [comment]
Oh of course! Nice to see things moving along. :) Did the invocation command find? If yes, where can I find that? Updating `deps.edn` and running `clojure -m pinkgorilla.core` gives me this:
```
Execution error (FileNotFoundException) at clojure.main/main (main.java:40).
Could not locate pinkgorilla/core__init.class, pinkgorilla/core.clj or pinkgorilla/core.cljc on classpath.

Full report at:
/tmp/clojure-154862377124214769.edn
```

So it probably moved somewhere from `pinkgorilla.core`, but I couldn't find it in the docs (the run command at the bottom of that page still uses `0.4.9`.)

**Comment by deas** [comment]
Appears we moved it to `pinkgorilla.notebook-app.core`. Sorry for the inconvenience.
 
https://github.com/pink-gorilla/gorilla-notebook/blob/master/project.clj#L171

**Comment by rrrnld** [comment]
Sorry this took so long! I just tried `0.4.17` and this bug doesn't seem to occur anymore.
