### ISSUE TITLE
Saved notebooks are not listed in explorer

### ISSUE THREAD

**Issue by rrrnld** [pink-gorilla/notebook#132]
I'm using pinkgorilla `0.4.17` via `deps.edn`. I noticed that when starting the notebook server via `clojure -Sdeps… -m pinkgorilla.otebook-app.core` I can't open the notebooks I saved -- at least it's not obvious to me. I tried different paths with no luck (project root, in `src` and in `notebooks`.

I am now using `pinkgorilla.embedded.run-notebook` to start the notebook server and pass in a custom `config.edn`. Is this expected?

`src/heyarne/notebooks.clj`:
``` clj
(ns heyarne.notebooks
  (:require [pinkgorilla.embedded :refer [run-notebook]]))

;; this namespace exists so we can define a ./config.edn; there is no other
;; (obvious) way to do this and our notebooks are not listed in the explorer
;; if we don't configure pinkgorilla accordingly

(defn -main [& args]
  (if (seq args)
    (run-notebook (first args))
    (run-notebook "./config.edn")))
```

`config.edn`:
``` clj
{:settings
 {:explore-repositories   [{:name "files" :url "/explore"}
                           #_{:name "public" :url "https://raw.githubusercontent.com/pink-gorilla/gorilla-explore/master/resources/list.json"}]
  :explore-file-directories {:python-gorilla "./notebooks"}}}
```

(this is taken and adapted from [this repo](https://github.com/pink-gorilla/python-gorilla/blob/579fe8dfc09107de1cfd2f766201e0fd244eab11/profiles/notebook/config.edn))

## Environment & Version information
See above.

### Java version
OpenJDK 1.8.0_252

### Operating system
Arch Linux, Linux Kernel 5.6.15

**Comment by awb99** [comment]
:explore-file-directories searches for .cljg notebooks in the path "./notebooks". If this files are valid gorilla notebooks, they will be added to the explorer view. I guess  you didnt save with "cljg" extension. The ui will be improved in an upcoming version.

You should see on app startup how many notebooks it has discovered in the console log.

Hope that helps :-)

**Comment by awb99** [comment]
new version has improved explorer. should not happen anymore.
