### ISSUE TITLE
Failed to read artifact descriptor for org.pinkgorilla:leinpinkgorilla:jar0.4.17

### ISSUE THREAD

**Issue by ramdhanhdy** [pink-gorilla/notebook#145]
I got the following error when try to run after installing for the first time. I'm a beginner on Clojure, so maybe I made a silly mistake. I setup by adding [org.pinkgorilla/gorilla-notebook "0.4.17"] on my project.clj file

![image](https://user-images.githubusercontent.com/25228812/117706417-756c4380-b1f7-11eb-94ca-33cc1c002328.png)

Gorilla-notebook version: 0.4.17

Operating system: Windows 10

**Comment by awb99** [comment]
You use windows. Unfortunately we don't support windows. There should not be a lot to make it work on windows though. Mainly paths. Perhaps @deas is happy to help there.

I uploaded a major upgrade today. I a updating docs the next couple of days.

**Comment by awb99** [comment]
we are moving to deps.edn
lein-pinkgorilla is dumped
