### ISSUE TITLE
Docker deployment 

### ISSUE THREAD

**Issue by awb99** [pink-gorilla/notebook#19]
1. Make 3449 port accessible from port 80 on outside
2. Mount /gorilla/sandbox from the host to /gorilla/sandbox on notebook. 
 Reason for sandbox: in the socket container there already is the cloned version of the sample-notebook project. I will ask daniel etc etc to make improvements and experiments to the Notebooks. We need to a) ensure they can savely safe Notebooks that survive a reboot of the pod and b) want to so upload somewhere else. I would do a Rsync somewhere or rclone to google drive or Dropbox that I trigger via cron. OR we just auto commit to a new sandbox git repo that would simply show the latest change of every file that was edited. That might be actually faster and more in line with our architecture.

Docker image uses jsu branch for now FYI. Currently master does not work with mist of the ui libraries that I use in the workbooks.

**Comment by deas** [comment]
This issue appears to be outdated.

**Comment by awb99** [comment]
@deas Thanks for adding this feature!
