### ISSUE TITLE
Great project 

### ISSUE THREAD

**Issue by awb99** [pink-gorilla/notebook#2]
Hi!

I am amazed of your improvements over the original gorilla repl! Thanks so much! 

I think now that we have reagent under the hood we could use this to allow for nice UI controls in gorilla repl! For example we could add sliders to limit the display of a big table. Or we could add an UI that collects parameter that will trigger the recalculation of a funcion / cell on the server.

We could go even a step further and display dynamically updating data from the server via a websocket.  Possibly we could write a routine that syncs server side atoms with client side atoms that arw then displayed in react. This would allow for a completely new level of interactive data analysis. 

And we could also add sub routes to each worksheet that would each display different data. 

We can so stuff that is eay mroe advanced than jupyter notebooks.

Are you interested to discuss this?

**Comment by deas** [comment]
Hi,

had a discussion with Jony (the original author) and Ben (the current maintainer) of the original gorilla-repl a while back. Both seemed to like my changes in general, but were quite busy at the time. For the time being, they chose to look how things turn out and keep doing basic maintainance for gorilla-repl. I got busier as well and also a bit worried whether it might not be a better idea piggybacking on jupyter, nteract or the like so the effort stalled. I'd love to see this thing evolve, but at the moment, I am also lacking a vision how it is supposed to differ from the other projects. And for sure, I won't be able to maintain traction just by myself. However, I would not hesitate to review and merge sane PRs. I may even get back pushing things forward once the vision is there.

**Comment by awb99** [comment]
I know you did :)  I read all your blog before writing you.

I love Jupyter. But I think it is very difficult to run Jupyter easily. I
developed some extensions to a c# engine years ago. And even with properly
setup docker containers it was never as easy as running a nrepl session.
This is why I think a pure clojure solution will have advantages.

Can we do a short whatsapp call?

**Comment by deas** [comment]
I'll get in touch via email.
