### ISSUE TITLE
ui/vega   (gorillaplot dvdt/xvsy oz)

### ISSUE THREAD

**Issue by awb99** [pink-gorilla/notebook#23]
DSL that creates Vega spec.
Similar idea and design as gorilla-plot.

https://github.com/dvdt/xvsy
https://github.com/dvdt/xvsy/tree/master/src/front-end
https://github.com/dvdt/gyptis/blob/master/src/cljc/gyptis/vega_templates.cljc
https://github.com/dvdt/gyptis/blob/master/examples/gyptis-usage/src/gyptis_usage/vega_interop.clj

Make it work with pink-gorilla.

**Comment by keesterbrugge** [comment]
I think a lot of value would already be created if we could give `vega` a clojure map instead of a url of a json file. I think this is the route that oz takes. 

```clojure
;; replace the url of spec
;; (def my-spec "https://raw.githubusercontent.com/vega/vega/master/docs/examples/bar-chart.vg.json")

;; with
(def my-spec 
{:data {:values [{:x 3 :y 4}]}
 :mark :point
 :encoding {:x {:field :x :type :quantitative} :y {:field :y :type :quantitative}}})

(reagent!
 '[:div
   [:p "sample vega plot:"]
  [vega my-spec]])
```

I would love to hear if this is already possible and I missed it.

**Comment by keesterbrugge** [comment]
and it would also enable changing the spec using a widget

**Comment by awb99** [comment]
Hi @keesterbrugge  !

We have 2 kernels (clj + cljs) which you can change for each cell. Vega is supported to be used
both from clj and from cljs kernel.

You can pass vega alternatively a string (then it is a url that it should load) or a clojure map
that contains the spec.

clj example:
http://localhost:9000/worksheet.html#/edit?source=repo&filename=notebooks/unittest/pinkgorilla-demo-vega.cljg&user=pink-gorilla&repo=gorilla-notebook

cljs:
If you use cljs, then you have all the interactivity of reagent available. So the vega chart
can rerender when the atom changes. I cannot find a sample right now, but it is the same
syntax and usage as the clj example :-)

We are experimenting how to link the two kernels. This is a test that uses widget state:
http://localhost:9000/worksheet.html#/edit?source=file&filename=./notebooks/reagent-manipulate.cljg
This demo shows all kind of advanced vega charts that are only possible with the recent version
of vega.
