### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by awb99** [pink-gorilla/notebook#26]
https://github.com/gadfly361/re-pressed
Any good?

**Comment by deas** [comment]
I think we should try to get close to Jupyther wrt Keybindings to ease user transition.

**Comment by awb99** [comment]
Keybindings have to be editable. There are too many browser plugins and what not so that the whole notebook befomes unusable id one important Keybinding soes not work

**Comment by awb99** [comment]
A dialog window that shows all keybindings in a more appealing format would be nice

**Comment by awb99** [comment]
This is still unresolved: In Firefox 69 Quantum: It shows the save-file dialog but then shows the Firefox menu "History/Show All History". Very annoying. Slows down the workflow incredibly. :-( BUT: I can save stuff.

In chromium nothing works at all. But this is most likely due to me using some chromium plugins that
are not compatible.

**Comment by deas** [comment]
FWIW: Meanwhile we support keybinding configuration using the edn configuration file.
