### ISSUE TITLE
pprint-table / newline character

### ISSUE THREAD

**Issue by awb99** [pink-gorilla/notebook#34]
https://github.com/pink-gorilla/sample-notebooks/blob/master/samples/fuckup-pprint.clj

if there is a newline \n character in a string, then only one line gets printed.

**Comment by awb99** [comment]
# 1. NREPL BUG
Evaling in the repl something that produces multiple lines will only return the last line 
Refrisk:
```
{
:id :4cc03ce2-e9f0-44ae-8ce7-4516c2f115ed
:type :code
:kernel :default-clj
:content {
:value "; this should print multiple rows. but it only shows the last row.\n(clojure.pprint/print-table data)"
:type "text/x-clojure"
}
:console-response "| christian | replikativ |\n"
```

# 2. REAGENT BUG

I have bypassed the first bug by using with-out-str 
(with-out-str (clojure.pprint/print-table data))

In Refrisk:

```
:console-response
"\r\n| :name | :speciality |\r\n|---------------------+-------------|\r\n| william shakespeare | novels |\r\n| rich hickie | clojure |\r\n| christian | replikativ |\r\n"
```
In DOM:
```
<div class="console-text">|           christian |  replikativ |
</div>
```

**Comment by awb99** [comment]
Added a hack for print-table.
The component that renders \n to br (called "text") is already a reagent component, so will remain after the print-table hack is removed. 

https://github.com/pink-gorilla/gorilla-notebook/commit/0c750e535555b12ced5520e867bea1f51c0c88b0

**Comment by awb99** [comment]
I just fixed this. Lets see if the commit message closes this ticket

**Comment by deas** [comment]
Check [Closing issues using keywords](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords)

**Comment by awb99** [comment]
This issue is fixed. Console output now gets rendered to multiple lines. This issue should have closed automatically, but didn't.
