### ISSUE TITLE
notebook ui redesign

### ISSUE THREAD

**Issue by awb99** [pink-gorilla/notebook#61]
observablehq has nicer ui:

https://observablehq.com/@observablehq/observables-not-javascript

- input can be hidden for any code cell; only output is visible always.
  by having this distinction, markup processing can be moved to a dedicated kernel,  and
  the ui  for markdown is identical to the ui of other kernels.

- slick white design, no massive notebook style layout. The view gets on creating a 
document that also has nice clean layout, not so much on a input-output mode of operation.
when we have reagent cells I am definitely not interested to view the sourcecode definition of
how the ui component works.

- code cells have an output -> the name and parameters of the functions that were
defined in the input - this is very nice view and rescues us being bothered by looking
inside the cell.

- cell reordering by drag and drop (I dont think this is an immediately important feature though).

**Comment by daslu** [comment]
Maria is also worth looking into:
https://www.maria.cloud/gallery?eval=true

**Comment by awb99** [comment]
excellent link - thanks @daslu

**Comment by awb99** [comment]
all ideas absorved
