### ISSUE TITLE
libpython bootstrapping woes

### ISSUE THREAD

**Issue by deas** [pink-gorilla/notebook#76]
We see various issues bootstrapping libpython and numpy. We consider numpy and pandas essential with regards to python conversions.

Appears current version `[cnuernber/libpython-clj "1.13"]` has a strict python3.6 requirement and Ubuntu has special lib_apt quirks. Had a hard time figuring things out on Ubuntu 19.10.

Other than that, it appears dynamical (pomegranate based) loading it from the repl does not work either.

## Expected behavior
Python initialization somehow working

## Actual behavior
Python initialization failing

## Environment & Version information
libpython-1.13

### gorilla-notebook version

f82e54cc9bd4f66622a2ffb1a56617119bc6cb03

### Java version

E.g. 1.8

### Operating system

n/a

**Comment by awb99** [comment]
dynamical loading works. It did not work due to C interop dependencies in clojure core that were outdted. project.clj in notebook has notes on it.
