### ISSUE TITLE
ClojureScript kernel is not "evaluate all" safe

### ISSUE THREAD

**Issue by deas** [pink-gorilla/notebook#93]
## Expected behavior
Notebook evaluates w/o errors

## Actual behavior
```
#error {:message "Could not eval my.klipse", :data {:tag :cljs/analysis-error}, :cause #error {:message nil, :data {:clojure.error/source nil, :clojure.error/line nil, :clojure.error/column nil, :clojure.error/phase :compilation}, :cause #error {:message "Cannot read property 'findInternedVar' of null", :data {:tag :cljs/analysis-error}, :cause #object[TypeError TypeError: Cannot read property 'findInternedVar' of null]}}}
```
## Steps to reproduce the problem
Open [bodymass-index.cljg](http://localhost:9000/worksheet.html#/edit?source=repo&filename=samples/cljs/bodymass-index.cljg&user=pink-gorilla&repo=sample-notebooks) and run "evaluate all".

### gorilla-notebook version
0.4.1-SNAPSHOT

### Java version
n/a

### Operating system
n/a

**Comment by awb99** [comment]
fixed. see pinkie branch
