### ISSUE TITLE
leaflet (clojure kernel based) not rendering maps

### ISSUE THREAD

**Issue by deas** [pink-gorilla/notebook#94]
## Expected behavior
Maps rendering

## Actual behavior
value returned from repl has `type` `html` and "proper" string value with a div and js. Appears injected JavaScript is not executed.

## Steps to reproduce the problem
Open [leaflet_err_javascript_inject.cljg](http://localhost:9000/worksheet.html#/edit?source=file&filename=./notebooks/unittest/leaflet_err_javascript_inject.cljg) and run "evaluate all".

### gorilla-notebook version
0.4.1-SNAPSHOT

### Java version
n/a

### Operating system
n/a

**Comment by awb99** [comment]
leaflet renderer is in gorilla-ui.
there is an old js renderer that is still out there; some of its features need to be ported over
sample is in gorilla-ui
