### ISSUE TITLE
Reagent based visualization should not depend on ClojureScript kernel

### ISSUE THREAD

**Issue by deas** [pink-gorilla/notebook#95]
## Expected behavior

leaflet, aggrid, player and sparkline visualisations rendering without clojure kernel

## Actual behavior
reagent based visualisation not supported without ClojureScript kernel

### gorilla-notebook version
0.4.1-SNAPSHOT

### Java version
n/a

### Operating system
n/a

**Comment by awb99** [comment]
clojurescript kernel is NOT needed to render any ui component.
The only thing where clojurescript is currently needed is advanced ui interaction (say making a calculation on a state change).
