### ISSUE TITLE
pink-gorilla.org is down

### ISSUE THREAD

**Issue by onetom** [pink-gorilla/notebook#98]
http://pink-gorilla.org/ is down (at least from Hong Kong).

The domain itself is not resolvable via Google DNS or CloudFlare:

```
$ host -av pink-gorilla.org 8.8.8.8
Trying "pink-gorilla.org"
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases:

Host pink-gorilla.org not found: 3(NXDOMAIN)
Received 97 bytes from 8.8.8.8#53 in 59 ms
Received 97 bytes from 8.8.8.8#53 in 59 ms

$ host -ta pink-gorilla.org 1.1.1.1
Using domain server:
Name: 1.1.1.1
Address: 1.1.1.1#53
Aliases:

Host pink-gorilla.org not found: 3(NXDOMAIN)
```

I was [instructed on Zulip chat](https://clojurians.zulipchat.com/#narrow/stream/212578-pink-gorilla-dev/topic/Arbitrary.20data.20render/near/185479858) to file an issue here.

**Comment by deas** [comment]
The domain is `pinkgorilla.org`, not `pink-gorilla.org`.

There are in fact a few issues with the name which has already been taken in some places. The github org is `pink-gorilla`, at dockerhub we are `pinkgorillawb` and so on.

With regards to our website, at this time, there is not yet a lot to see, but we aim at hosting a demo there "soon".

For the moment, my highest prio is cleaning things up to improve ux - for devs and users. I expect merging to master this week and "release" a new thing for people to try out.
